spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-pw  # Change this to your MySQL password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jakarta:
        persistence:
          validation:
            mode: auto
  security:
    filter:
      order: 10

jwt:
  secret: QUJDREVGMTIzNDU2Nzg5MCFAIyQlXiYqKClfKy09P34=
  expiration: 86400000

server:
  port: 8080 

logging:
  level:
    root: INFO
    com.example.authservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

messages:
  basename: validation
  encoding: UTF-8